spring.application.name=discovery-server

# البورت اللي السيرفر هيشتغل عليه (8761 هو الرقم المتعارف عليه لـ Eureka)
server.port=8761

# بنقول للسيرفر "متسجلش نفسك كـ Client" لأنك أنت السيرفر الكبير
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false